version: "2"
services:
  node:
    # image: "node:8"
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"

# ubuntu based image
# All { npm, yarn, npx } are installed
# git, diff, python2/3, bash